:arrow_up: statsmodels 0.14.5
This may resolve a scipy 1.16 update error:
>   File "/usr/local/lib/python3.11/site-packages/statsmodels/api.py", line 78, in <module>
    from . import datasets, distributions, iolib, regression, robust, tools
  File "/usr/local/lib/python3.11/site-packages/statsmodels/distributions/__init__.py", line 7, in <module>
    from .discrete import (
  File "/usr/local/lib/python3.11/site-packages/statsmodels/distributions/discrete.py", line 5, in <module>
    from scipy._lib._util import _lazywhere
ImportError: cannot import name '_lazywhere' from 'scipy._lib._util' (/usr/local/lib/python3.11/site-packages/scipy/_lib/_util.py)